version: '3.8'

services:
  discord-bot:
    build: .
    container_name: mon_bot_discord
    restart: unless-stopped
    environment:
      # Force Python à afficher les logs en temps réel
      - PYTHONUNBUFFERED=1
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GOOGLE_SHEETS_CREDENTIALS=${GOOGLE_SHEETS_CREDENTIALS}
